apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    app: blogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapi
  template:
    metadata:
      labels:
        app: blogapi
    spec:
      containers:
      - name: blogapi
        image: middlwarecontainerresgt.azurecr.io/blogapi:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DatabaseSettings__ConnectionString
          valueFrom: 
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
---
apiVersion: v1
kind: Service
metadata:
  name: blogapi-service
spec:
  
  selector:
    app: blogapi
  ports:
    - protocol: TCP
      port: 80
     