apiVersion: apps/v1
kind: Deployment
metadata:
  name: manipmcv-deployment
  labels:
    app: manipmcv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manipmcv
  template:
    metadata:
      labels:
        app: manipmcv
    spec:
      containers:
      - name: manipmcv
        image: middlwarecontainerresgt.azurecr.io/manipulation:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DatabaseSettings__ConnectionString
          valueFrom: 
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
        - name: SERVICEBUS_CONNECTIONSTRING
          value: "Endpoint=sb://servicebusxyz.servicebus.windows.net/;SharedAccessKeyName=keda-aks-01;SharedAccessKey=KwC4VLTQu1TjS3BHpB17FQVMuq6xd8h+y4dPa1djuwU=;EntityPath=Queue"

---
apiVersion: v1
kind: Service
metadata:
  name: manipmcv-service
spec:
  type: LoadBalancer
  selector:
    app: manipmcv
  ports:
    - protocol: TCP
      port: 80
      
